Feature/36558/st george old import mising records
NHSDigital/data_management_system pull request #123
Opened 2024-10-31 10:50 UTC by NImeson

**What?**
Adding in functionality to import UCS variants add in the test status 10 value when recording the status of variant results. Expanding the regular expressions to account for missing SRIs.  Deal with missing SRIs where there is an abornal variant but no gene to assign it to. 

**Why?**
There are 64 records that are not currently being imported from the raw files into MBIS / CASREF. These records are large;ly abnormal results that which we really do want to capture.

Need to broaden the regex that assigns a teststatus as 2. To include fields that contain strings such as 'IVS' or 'Del X 5-7'.
Include functionality to import UCS variants and give them teststatus 10 outcome
Incorpoate functionality to import abnormal variants where the gene is unknown (also create additional empty tests for BRCA1+2 where these are full screen)

**How?**
Added in method to ctreate BRCA1/2 records as standard when we don't know what the FS gene in question is .
Added in method to handle a variant when we don't know the gene it belongs to
Expanded to exon regex to account for additional variant nomenclatures eg. IVS, DEL X 5-7
Added in functionality to import UCS variants and give them test status 10 value

**Testing?**

All missing SRIs are now being being imported with the exception of one, which has a 'nil' field (would need more substantial changes to importer). Variants for each missing SRI are being imported to some extent (it's difficult to fully import some as the way they are written conflicts with importer rules). 

Variant counts between existing importer and this version show additional SRIs across the board, mostly the expected missing SRIs but also exra ones. Extra counts have been investigated and importer is performing correctly with these records. 

Additional QA checks completed looking at number of variant entries across a varierty of metrics.testing has shown that the changes now include more cDNA variants, protein variants, exonintron variants than previously.

2025-01-27 11:45 UTC, shilpigoeldev requested changes

2025-01-27 11:45 UTC, shilpigoeldev commented on lib/import/brca/providers/st_george_old/st_george_handler_old.rb
> +            genotype.add_gene(positive_genes.join)
Should it be called _positive_gene_ as I understand its a single gene that's getting added here ?

2025-01-27 11:45 UTC, shilpigoeldev commented on lib/import/brca/providers/st_george_old/st_george_handler_old.rb
> +            create_empty_brca_tests(genotype, genotypes) if positive_genes.empty? # create teststatus 4 records for BRCA1/2 to capture they have been tested.
if positive_gene is empty -> negative_gene will evaluate to  %w[BRCA1 BRCA2] and then above code which executes first "genotype_dup.add_gene(negative_gene.join)" will be incorrect ..

2025-01-27 11:49 UTC, NImeson commented on lib/import/brca/providers/st_george_old/st_george_handler_old.rb
> +            genotype.add_gene(positive_genes.join)
So it's adding two genes here, BRCA1 and 2 are always added for full screen tests. In these examples, the genotype field might state e.g. 'BR2 UCS' so there is a 'positive gene' which will be test status 10 and then the other one (BRCA1 in this example) would need adding as well with teststatus 1.

2025-01-27 16:49 UTC, NImeson commented on lib/import/brca/providers/st_george_old/st_george_handler_old.rb
> +            genotype.add_gene(positive_genes.join)
Edited this in latest commit to account for the potential for there to be multiple genes in the positive_genes array.

2025-01-29 15:35 UTC, shilpigoeldev requested changes
I think we are also missing the test case discussed today multi_variants_no_gene fullscreen case ..

2025-01-29 15:35 UTC, shilpigoeldev commented on lib/import/brca/providers/st_george_old/st_george_handler_old.rb
> +              genotype.add_gene(positive_genes.join) if !positive_genes.nil?
Aren't we adding same gene twice here ? from method definition looks like positive_genes and gene added via process_single_gene are scanning for gene same way .. worth doing a `pry` here to see if we are making call to add_gene twice here ..

2025-01-29 15:35 UTC, shilpigoeldev commented on test/lib/import/brca/providers/st_george_old/st_george_handler_old_test.rb
> +    @logger.expects(:debug).with('SUCCESSFUL gene parse for BRCA2')
We want assertions in tests rather depending on logging statements, can that be changed for this file please.. TIA

2025-01-30 12:44 UTC, NImeson commented on lib/import/brca/providers/st_george_old/st_george_handler_old.rb
> +              genotype.add_gene(positive_genes.join) if !positive_genes.nil?
I don't think it actually ever does anything in process_single_gene(), I think it was always go to the else clause in that method as it wouldn't match any of the other conditions. unknown_status() will only be invoked when there is a gene in the genotype field but potentially nothing else that we can make sense of. I think process_single_gene is just in there as a hangover from previous code iterations so can be removed?

2025-01-30 13:50 UTC, NImeson commented on lib/import/brca/providers/st_george_old/st_george_handler_old.rb
> +              genotype.add_gene(positive_genes.join) if !positive_genes.nil?
Removed call to run process_single_gene() - think this might be a hangover from a previous code iteration, it isn't needed as positive_genes already contains the 'processed' gene in question. Edited in latest commit [56d78c9](https://github.com/NHSDigital/data_management_system/pull/123/commits/56d78c99d043b3b9180cca3ea45042b67e1a73dd)

2025-01-30 13:51 UTC, NImeson commented on test/lib/import/brca/providers/st_george_old/st_george_handler_old_test.rb
> +    @logger.expects(:debug).with('SUCCESSFUL gene parse for BRCA2')
Removed logger statements from test methods in commit [19d97a6](https://github.com/NHSDigital/data_management_system/pull/123/commits/19d97a6edc4709de2b3b185083fda75f70360bc1)

2025-01-30 13:52 UTC, NImeson commented on lib/import/brca/providers/st_george_old/st_george_handler_old.rb
> +            create_empty_brca_tests(genotype, genotypes) if positive_genes.empty? # create teststatus 4 records for BRCA1/2 to capture they have been tested.
Edited in [8fce60c](https://github.com/NHSDigital/data_management_system/pull/123/commits/8fce60c658cf39bcf388e12ec7f5d3e9b056acf7)

2025-01-31 18:06 UTC, shilpigoeldev reviewed
LGTM now , but pending Fiona confirmation on QA so can approve and merge once Fiona's approval comes in. Thanks @NImeson !!

2025-03-24 16:52 UTC, shilpigoeldev approved these changes
Fiona has approved QA now!!

2025-03-24 16:56 UTC, merged