Feature/liverpool restructure
NHSDigital/data_management_system pull request #25
Opened 2023-08-25 09:02 UTC by lauramccluskey1

Updates have been made to the Liverpool importers. Test status and test scope in the constants files, and the investigation field in the handler files, have been updated for both brca and colorectal. The changes have all passed QA and the files have passed through rubocop.

2023-08-30 14:51 UTC, shilpigoeldev requested changes

2023-09-01 10:45 UTC, lauramccluskey1 commented on lib/import/brca/providers/liverpool/liverpool_handler.rb
> +            colorectal_cases = /HNPCC|Peutz(-|\s)Jegher\sSyndrome|Lynch\ssyndrome/i
These changes have now been made- the importers have also been rerun to check that there are no changes to the variant counts.

2023-09-01 10:46 UTC, shilpigoeldev commented on lib/import/brca/providers/liverpool/liverpool_handler.rb
> +            colorectal_cases = /HNPCC|Peutz(-|\s)Jegher\sSyndrome|Lynch\ssyndrome/i
Thanks @lauramccluskey1

2023-09-01 10:46 UTC, shilpigoeldev approved these changes

2023-09-01 10:49 UTC, shilpigoeldev approved these changes
Looks all good to me.

2023-09-07 13:04 UTC, merged