Feature/35204/newcastle importer
NHSDigital/data_management_system pull request #43
Opened 2023-11-09 11:52 UTC by lauramccluskey1

Functionality to add test status of 10 to benign, likely benign and non-pathological variants. Unittests have been updated and run ok for the Newcastle importer. Couple of integration issues when running all unittests- these have been flagged to @shilpigoeldev. Variant counts QA has been completed and checked.

2023-11-09 15:14 UTC, shilpigoeldev requested changes
Can you look into rubocop fixes for lib/import/helpers/brca/providers/rtd/rtd_constants.rb

2023-11-09 15:14 UTC, shilpigoeldev commented on test/lib/import/brca/providers/newcastle/newcastle_handler_test.rb
> +    noscope_genemutation_record = build_raw_record('pseudo_id1' => 'bob')
Can you keep the name for records align with their attribute like done in colorectal tests -  benign_record, likely_benign_record , thanks

2023-11-10 14:21 UTC, lauramccluskey1 commented
Changes requested in code review have now been made

2023-11-10 14:53 UTC, shilpigoeldev approved these changes
LGTM

2023-11-10 14:54 UTC, merged